import React, { createContext, useContext, useState } from 'react';

export type Language = 'EN' | 'SW' | 'ES' | 'FR' | 'CN' | 'DE' | 'IT' | 'PT' | 'RU' | 'JA' | 'KO' | 'AR' | 'HI' | 'TR' | 'NL' | 'SV' | 'NO' | 'DA' | 'FI' | 'PL' | 'CS' | 'HU' | 'RO' | 'BG' | 'HR' | 'SR' | 'SK' | 'SL' | 'ET' | 'LV' | 'LT' | 'MT' | 'EL' | 'HE' | 'TH' | 'VI' | 'ID' | 'MS' | 'TL' | 'BN' | 'UR' | 'FA' | 'PS' | 'KU' | 'AM' | 'NE' | 'SI' | 'MY' | 'KM' | 'LO';

const translations: Record<Language, Record<string, string>> = {
  EN: {
    good_morning: 'Good Morning',
    good_afternoon: 'Good Afternoon',
    good_evening: 'Good Evening',
    home: 'Home',
    services: 'Services',
    showroom: 'Showroom',
    company: 'Company',
    news: 'News',
    successStories: 'Success Stories',
    about: 'About Us',
    contact: 'Contact Us',
    register: 'Register',
    login: 'Login',
    logout: 'Logout',
    toggleTheme: 'Toggle Theme',
    language: 'Language',
    welcome: 'Welcome to Justice Ultimate Automobiles',
    unlock: 'Unlock Full Access',
    contactUs: 'Contact Us',
    admin: 'Admin',
    administrator: 'Administrator',
    adminProfile: 'Admin Profile',
    dashboard: 'Dashboard',
    carsManagement: 'Cars Management',
    businessHub: 'Business Hub',
    analytics: 'Analytics',
    receipts: 'Receipts',
    userManagement: 'User Management',
    transactions: 'Transactions',
    settings: 'System Settings',
    staffPanel: 'Staff Panel',
    departments: 'Departments',
    inventory: 'Inventory',
    activityLogs: 'Activity Logs',
    branches: 'Branches',
    returnToDashboard: 'Return to Dashboard',
    help: 'Help',
    support: 'Support',
    tutorials: 'Tutorials',
    documentation: 'Documentation',
    systemGuide: 'System Guide',
    roleBasedHelp: 'Role-Based Help',
    customerService: 'Customer Service',
    afterSales: 'After Sales',
    warranty: 'Warranty',
    maintenance: 'Maintenance',
    financing: 'Financing',
    insurance: 'Insurance',
    roadsideAssistance: 'Roadside Assistance',
    // ...add more as needed
  },
  SW: {
    good_morning: 'Habari ya Asubuhi',
    good_afternoon: 'Habari ya Mchana',
    good_evening: 'Habari ya Jioni',
    home: 'Nyumbani',
    services: 'Huduma',
    showroom: 'Ghala la Magari',
    company: 'Kampuni',
    news: 'Habari',
    successStories: 'Hadithi za Mafanikio',
    about: 'Kuhusu Sisi',
    contact: 'Wasiliana Nasi',
    register: 'Jisajili',
    login: 'Ingia',
    logout: 'Toka',
    toggleTheme: 'Badilisha Mandhari',
    language: 'Lugha',
    welcome: 'Karibu Justice Ultimate Automobiles',
    unlock: 'Fungua Ufikiaji Kamili',
    contactUs: 'Wasiliana Nasi',
    admin: 'Msimamizi',
    administrator: 'Msimamizi Mkuu',
    adminProfile: 'Wasifu wa Admin',
    dashboard: 'Dashibodi',
    carsManagement: 'Usimamizi wa Magari',
    businessHub: 'Kitovu cha Biashara',
    analytics: 'Takwimu',
    receipts: 'Risiti',
    userManagement: 'Usimamizi wa Watumiaji',
    transactions: 'Miamala',
    settings: 'Mipangilio ya Mfumo',
    staffPanel: 'Paneli ya Wafanyakazi',
    departments: 'Idara',
    inventory: 'Hisa',
    activityLogs: 'Rekodi za Shughuli',
    branches: 'Matawi',
    returnToDashboard: 'Rudi kwenye Dashibodi',
    help: 'Msaada',
    support: 'Msaada',
    tutorials: 'Mafunzo',
    documentation: 'Nyaraka',
    systemGuide: 'Mwongozo wa Mfumo',
    roleBasedHelp: 'Msaada wa Jukumu',
    customerService: 'Huduma ya Wateja',
    afterSales: 'Baada ya Uuzaji',
    warranty: 'Dhamana',
    maintenance: 'Matengenezo',
    financing: 'Fedha',
    insurance: 'Bima',
    roadsideAssistance: 'Msaada wa Barabarani',
    // ...add more as needed
  },
  ES: {
    good_morning: 'Buenos Días',
    good_afternoon: 'Buenas Tardes',
    good_evening: 'Buenas Noches',
    home: 'Inicio',
    services: 'Servicios',
    showroom: 'Sala de Exhibición',
    company: 'Compañía',
    news: 'Noticias',
    successStories: 'Historias de Éxito',
    about: 'Sobre Nosotros',
    contact: 'Contáctanos',
    register: 'Registrarse',
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    toggleTheme: 'Cambiar Tema',
    language: 'Idioma',
    welcome: 'Bienvenido a Justice Ultimate Automobiles',
    unlock: 'Desbloquear Acceso Completo',
    contactUs: 'Contáctanos',
    admin: 'Administrador',
    administrator: 'Administrador',
    adminProfile: 'Perfil de Admin',
    dashboard: 'Panel',
    carsManagement: 'Gestión de Autos',
    businessHub: 'Centro de Negocios',
    analytics: 'Analítica',
    receipts: 'Recibos',
    userManagement: 'Gestión de Usuarios',
    transactions: 'Transacciones',
    settings: 'Configuración del Sistema',
    staffPanel: 'Panel de Personal',
    departments: 'Departamentos',
    inventory: 'Inventario',
    activityLogs: 'Registros de Actividad',
    branches: 'Sucursales',
    returnToDashboard: 'Volver al Panel',
    help: 'Ayuda',
    support: 'Soporte',
    tutorials: 'Tutoriales',
    documentation: 'Documentación',
    systemGuide: 'Guía del Sistema',
    roleBasedHelp: 'Ayuda por Rol',
    customerService: 'Servicio al Cliente',
    afterSales: 'Postventa',
    warranty: 'Garantía',
    maintenance: 'Mantenimiento',
    financing: 'Financiamiento',
    insurance: 'Seguro',
    roadsideAssistance: 'Asistencia Vial',
    // ...add more as needed
  },
  FR: {
    good_morning: 'Bonjour',
    good_afternoon: 'Bon après-midi',
    good_evening: 'Bonsoir',
    home: 'Accueil',
    services: 'Services',
    showroom: 'Salle d\'Exposition',
    company: 'Entreprise',
    news: 'Actualités',
    successStories: 'Histoires de Réussite',
    about: 'À Propos',
    contact: 'Contactez-nous',
    register: 'S\'inscrire',
    login: 'Se Connecter',
    logout: 'Se Déconnecter',
    toggleTheme: 'Changer de Thème',
    language: 'Langue',
    welcome: 'Bienvenue chez Justice Ultimate Automobiles',
    unlock: 'Débloquer l\'Accès Complet',
    contactUs: 'Contactez-nous',
    admin: 'Administrateur',
    administrator: 'Administrateur',
    adminProfile: 'Profil Admin',
    dashboard: 'Tableau de Bord',
    carsManagement: 'Gestion des Voitures',
    businessHub: 'Centre d\'Affaires',
    analytics: 'Analytique',
    receipts: 'Reçus',
    userManagement: 'Gestion des Utilisateurs',
    transactions: 'Transactions',
    settings: 'Paramètres Système',
    staffPanel: 'Panel du Personnel',
    departments: 'Départements',
    inventory: 'Inventaire',
    activityLogs: 'Journaux d\'Activité',
    branches: 'Succursales',
    returnToDashboard: 'Retour au Tableau de Bord',
    help: 'Aide',
    support: 'Support',
    tutorials: 'Tutoriels',
    documentation: 'Documentation',
    systemGuide: 'Guide du Système',
    roleBasedHelp: 'Aide par Rôle',
    customerService: 'Service Client',
    afterSales: 'Service Après-Vente',
    warranty: 'Garantie',
    maintenance: 'Maintenance',
    financing: 'Financement',
    insurance: 'Assurance',
    roadsideAssistance: 'Assistance Routière',
    // ...add more as needed
  },
  CN: {
    good_morning: '早上好',
    good_afternoon: '下午好',
    good_evening: '晚上好',
    home: '首页',
    services: '服务',
    showroom: '展厅',
    company: '公司',
    news: '新闻',
    successStories: '成功故事',
    about: '关于我们',
    contact: '联系我们',
    register: '注册',
    login: '登录',
    logout: '登出',
    toggleTheme: '切换主题',
    language: '语言',
    welcome: '欢迎来到正义终极汽车',
    unlock: '解锁完整访问',
    contactUs: '联系我们',
    admin: '管理员',
    administrator: '系统管理员',
    adminProfile: '管理员资料',
    dashboard: '仪表板',
    carsManagement: '汽车管理',
    businessHub: '商业中心',
    analytics: '分析',
    receipts: '收据',
    userManagement: '用户管理',
    transactions: '交易',
    settings: '系统设置',
    staffPanel: '员工面板',
    departments: '部门',
    inventory: '库存',
    activityLogs: '活动日志',
    branches: '分支机构',
    returnToDashboard: '返回仪表板',
    help: '帮助',
    support: '支持',
    tutorials: '教程',
    documentation: '文档',
    systemGuide: '系统指南',
    roleBasedHelp: '基于角色的帮助',
    customerService: '客户服务',
    afterSales: '售后服务',
    warranty: '保修',
    maintenance: '维护',
    financing: '融资',
    insurance: '保险',
    roadsideAssistance: '道路救援',
    // ...add more as needed
  },
  DE: {
    good_morning: 'Guten Morgen',
    good_afternoon: 'Guten Tag',
    good_evening: 'Guten Abend',
    home: 'Startseite',
    services: 'Dienstleistungen',
    showroom: 'Ausstellungsraum',
    company: 'Unternehmen',
    news: 'Nachrichten',
    successStories: 'Erfolgsgeschichten',
    about: 'Über uns',
    contact: 'Kontakt',
    register: 'Registrieren',
    login: 'Anmelden',
    logout: 'Abmelden',
    toggleTheme: 'Theme wechseln',
    language: 'Sprache',
    welcome: 'Willkommen bei Justice Ultimate Automobiles',
    unlock: 'Vollzugriff freischalten',
    contactUs: 'Kontaktieren Sie uns',
    admin: 'Administrator',
    administrator: 'Administrator',
    adminProfile: 'Admin-Profil',
    dashboard: 'Dashboard',
    carsManagement: 'Fahrzeugverwaltung',
    businessHub: 'Geschäftszentrum',
    analytics: 'Analytik',
    receipts: 'Quittungen',
    userManagement: 'Benutzerverwaltung',
    transactions: 'Transaktionen',
    settings: 'Systemeinstellungen',
    staffPanel: 'Personal-Panel',
    departments: 'Abteilungen',
    inventory: 'Inventar',
    activityLogs: 'Aktivitätsprotokolle',
    branches: 'Niederlassungen',
    returnToDashboard: 'Zum Dashboard zurückkehren',
    help: 'Hilfe',
    support: 'Support',
    tutorials: 'Tutorials',
    documentation: 'Dokumentation',
    systemGuide: 'Systemanleitung',
    roleBasedHelp: 'Rollenbasierte Hilfe',
    customerService: 'Kundenservice',
    afterSales: 'After-Sales',
    warranty: 'Garantie',
    maintenance: 'Wartung',
    financing: 'Finanzierung',
    insurance: 'Versicherung',
    roadsideAssistance: 'Pannenhilfe',
    // ...add more as needed
  },
  IT: {
    good_morning: 'Buongiorno',
    good_afternoon: 'Buon pomeriggio',
    good_evening: 'Buonasera',
    home: 'Home',
    services: 'Servizi',
    showroom: 'Sala Esposizioni',
    company: 'Azienda',
    news: 'Notizie',
    successStories: 'Storie di Successo',
    about: 'Chi Siamo',
    contact: 'Contatti',
    register: 'Registrati',
    login: 'Accedi',
    logout: 'Esci',
    toggleTheme: 'Cambia Tema',
    language: 'Lingua',
    welcome: 'Benvenuto in Justice Ultimate Automobiles',
    unlock: 'Sblocca Accesso Completo',
    contactUs: 'Contattaci',
    admin: 'Amministratore',
    administrator: 'Amministratore',
    adminProfile: 'Profilo Admin',
    dashboard: 'Dashboard',
    carsManagement: 'Gestione Auto',
    businessHub: 'Centro Affari',
    analytics: 'Analitica',
    receipts: 'Ricevute',
    userManagement: 'Gestione Utenti',
    transactions: 'Transazioni',
    settings: 'Impostazioni Sistema',
    staffPanel: 'Panel Personale',
    departments: 'Dipartimenti',
    inventory: 'Inventario',
    activityLogs: 'Log Attività',
    branches: 'Filiali',
    returnToDashboard: 'Torna alla Dashboard',
    help: 'Aiuto',
    support: 'Supporto',
    tutorials: 'Tutorial',
    documentation: 'Documentazione',
    systemGuide: 'Guida Sistema',
    roleBasedHelp: 'Aiuto per Ruolo',
    customerService: 'Servizio Clienti',
    afterSales: 'Post-Vendita',
    warranty: 'Garanzia',
    maintenance: 'Manutenzione',
    financing: 'Finanziamento',
    insurance: 'Assicurazione',
    roadsideAssistance: 'Assistenza Stradale',
    // ...add more as needed
  },
  PT: {
    good_morning: 'Bom Dia',
    good_afternoon: 'Boa Tarde',
    good_evening: 'Boa Noite',
    home: 'Início',
    services: 'Serviços',
    showroom: 'Sala de Exposição',
    company: 'Empresa',
    news: 'Notícias',
    successStories: 'Histórias de Sucesso',
    about: 'Sobre Nós',
    contact: 'Contato',
    register: 'Registrar',
    login: 'Entrar',
    logout: 'Sair',
    toggleTheme: 'Alternar Tema',
    language: 'Idioma',
    welcome: 'Bem-vindo à Justice Ultimate Automobiles',
    unlock: 'Desbloquear Acesso Completo',
    contactUs: 'Entre em Contato',
    admin: 'Administrador',
    administrator: 'Administrador',
    adminProfile: 'Perfil Admin',
    dashboard: 'Painel',
    carsManagement: 'Gestão de Carros',
    businessHub: 'Centro de Negócios',
    analytics: 'Analytics',
    receipts: 'Recibos',
    userManagement: 'Gestão de Usuários',
    transactions: 'Transações',
    settings: 'Configurações do Sistema',
    staffPanel: 'Painel de Funcionários',
    departments: 'Departamentos',
    inventory: 'Inventário',
    activityLogs: 'Logs de Atividade',
    branches: 'Filiais',
    returnToDashboard: 'Voltar ao Painel',
    help: 'Ajuda',
    support: 'Suporte',
    tutorials: 'Tutoriais',
    documentation: 'Documentação',
    systemGuide: 'Guia do Sistema',
    roleBasedHelp: 'Ajuda por Função',
    customerService: 'Atendimento ao Cliente',
    afterSales: 'Pós-Venda',
    warranty: 'Garantia',
    maintenance: 'Manutenção',
    financing: 'Financiamento',
    insurance: 'Seguro',
    roadsideAssistance: 'Assistência na Estrada',
    // ...add more as needed
  },
  RU: {
    good_morning: 'Доброе утро',
    good_afternoon: 'Добрый день',
    good_evening: 'Добрый вечер',
    home: 'Главная',
    services: 'Услуги',
    showroom: 'Выставочный зал',
    company: 'Компания',
    news: 'Новости',
    successStories: 'Истории успеха',
    about: 'О нас',
    contact: 'Контакты',
    register: 'Регистрация',
    login: 'Вход',
    logout: 'Выход',
    toggleTheme: 'Переключить тему',
    language: 'Язык',
    welcome: 'Добро пожаловать в Justice Ultimate Automobiles',
    unlock: 'Разблокировать полный доступ',
    contactUs: 'Свяжитесь с нами',
    admin: 'Администратор',
    administrator: 'Администратор',
    adminProfile: 'Профиль админа',
    dashboard: 'Панель управления',
    carsManagement: 'Управление автомобилями',
    businessHub: 'Бизнес-центр',
    analytics: 'Аналитика',
    receipts: 'Квитанции',
    userManagement: 'Управление пользователями',
    transactions: 'Транзакции',
    settings: 'Настройки системы',
    staffPanel: 'Панель персонала',
    departments: 'Отделы',
    inventory: 'Инвентарь',
    activityLogs: 'Журналы активности',
    branches: 'Филиалы',
    returnToDashboard: 'Вернуться к панели',
    help: 'Помощь',
    support: 'Поддержка',
    tutorials: 'Учебники',
    documentation: 'Документация',
    systemGuide: 'Руководство по системе',
    roleBasedHelp: 'Помощь по ролям',
    customerService: 'Обслуживание клиентов',
    afterSales: 'Послепродажное обслуживание',
    warranty: 'Гарантия',
    maintenance: 'Обслуживание',
    financing: 'Финансирование',
    insurance: 'Страхование',
    roadsideAssistance: 'Дорожная помощь',
    // ...add more as needed
  },
  JA: {
    good_morning: 'おはようございます',
    good_afternoon: 'こんにちは',
    good_evening: 'こんばんは',
    home: 'ホーム',
    services: 'サービス',
    showroom: 'ショールーム',
    company: '会社',
    news: 'ニュース',
    successStories: '成功事例',
    about: '会社概要',
    contact: 'お問い合わせ',
    register: '登録',
    login: 'ログイン',
    logout: 'ログアウト',
    toggleTheme: 'テーマ切り替え',
    language: '言語',
    welcome: 'Justice Ultimate Automobilesへようこそ',
    unlock: 'フルアクセスを解除',
    contactUs: 'お問い合わせ',
    admin: '管理者',
    administrator: '管理者',
    adminProfile: '管理者プロフィール',
    dashboard: 'ダッシュボード',
    carsManagement: '車両管理',
    businessHub: 'ビジネスハブ',
    analytics: '分析',
    receipts: '領収書',
    userManagement: 'ユーザー管理',
    transactions: '取引',
    settings: 'システム設定',
    staffPanel: 'スタッフパネル',
    departments: '部門',
    inventory: '在庫',
    activityLogs: 'アクティビティログ',
    branches: '支店',
    returnToDashboard: 'ダッシュボードに戻る',
    help: 'ヘルプ',
    support: 'サポート',
    tutorials: 'チュートリアル',
    documentation: 'ドキュメント',
    systemGuide: 'システムガイド',
    roleBasedHelp: '役割別ヘルプ',
    customerService: 'カスタマーサービス',
    afterSales: 'アフターサービス',
    warranty: '保証',
    maintenance: 'メンテナンス',
    financing: 'ファイナンス',
    insurance: '保険',
    roadsideAssistance: 'ロードサイドアシスタンス',
    // ...add more as needed
  },
  KO: {
    good_morning: '좋은 아침입니다',
    good_afternoon: '안녕하세요',
    good_evening: '좋은 저녁입니다',
    home: '홈',
    services: '서비스',
    showroom: '쇼룸',
    company: '회사',
    news: '뉴스',
    successStories: '성공 사례',
    about: '회사 소개',
    contact: '연락처',
    register: '등록',
    login: '로그인',
    logout: '로그아웃',
    toggleTheme: '테마 전환',
    language: '언어',
    welcome: 'Justice Ultimate Automobiles에 오신 것을 환영합니다',
    unlock: '전체 액세스 해제',
    contactUs: '문의하기',
    admin: '관리자',
    administrator: '관리자',
    adminProfile: '관리자 프로필',
    dashboard: '대시보드',
    carsManagement: '차량 관리',
    businessHub: '비즈니스 허브',
    analytics: '분석',
    receipts: '영수증',
    userManagement: '사용자 관리',
    transactions: '거래',
    settings: '시스템 설정',
    staffPanel: '직원 패널',
    departments: '부서',
    inventory: '재고',
    activityLogs: '활동 로그',
    branches: '지점',
    returnToDashboard: '대시보드로 돌아가기',
    help: '도움말',
    support: '지원',
    tutorials: '튜토리얼',
    documentation: '문서',
    systemGuide: '시스템 가이드',
    roleBasedHelp: '역할별 도움말',
    customerService: '고객 서비스',
    afterSales: '애프터 서비스',
    warranty: '보증',
    maintenance: '유지보수',
    financing: '금융',
    insurance: '보험',
    roadsideAssistance: '도로 지원',
    // ...add more as needed
  },
  AR: {
    good_morning: 'صباح الخير',
    good_afternoon: 'مساء الخير',
    good_evening: 'مساء الخير',
    home: 'الرئيسية',
    services: 'الخدمات',
    showroom: 'معرض السيارات',
    company: 'الشركة',
    news: 'الأخبار',
    successStories: 'قصص النجاح',
    about: 'من نحن',
    contact: 'اتصل بنا',
    register: 'تسجيل',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    toggleTheme: 'تبديل المظهر',
    language: 'اللغة',
    welcome: 'مرحباً بكم في Justice Ultimate Automobiles',
    unlock: 'فتح الوصول الكامل',
    contactUs: 'اتصل بنا',
    admin: 'المدير',
    administrator: 'المدير',
    adminProfile: 'ملف المدير',
    dashboard: 'لوحة التحكم',
    carsManagement: 'إدارة السيارات',
    businessHub: 'مركز الأعمال',
    analytics: 'التحليلات',
    receipts: 'الإيصالات',
    userManagement: 'إدارة المستخدمين',
    transactions: 'المعاملات',
    settings: 'إعدادات النظام',
    staffPanel: 'لوحة الموظفين',
    departments: 'الأقسام',
    inventory: 'المخزون',
    activityLogs: 'سجلات النشاط',
    branches: 'الفروع',
    returnToDashboard: 'العودة إلى لوحة التحكم',
    help: 'المساعدة',
    support: 'الدعم',
    tutorials: 'الدروس التعليمية',
    documentation: 'الوثائق',
    systemGuide: 'دليل النظام',
    roleBasedHelp: 'المساعدة حسب الدور',
    customerService: 'خدمة العملاء',
    afterSales: 'ما بعد البيع',
    warranty: 'الضمان',
    maintenance: 'الصيانة',
    financing: 'التمويل',
    insurance: 'التأمين',
    roadsideAssistance: 'المساعدة على الطريق',
    // ...add more as needed
  },
  HI: {
    good_morning: 'सुप्रभात',
    good_afternoon: 'नमस्कार',
    good_evening: 'शुभ संध्या',
    home: 'होम',
    services: 'सेवाएं',
    showroom: 'शोरूम',
    company: 'कंपनी',
    news: 'समाचार',
    successStories: 'सफलता की कहानियां',
    about: 'हमारे बारे में',
    contact: 'संपर्क करें',
    register: 'पंजीकरण',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    toggleTheme: 'थीम बदलें',
    language: 'भाषा',
    welcome: 'Justice Ultimate Automobiles में आपका स्वागत है',
    unlock: 'पूर्ण पहुंच अनलॉक करें',
    contactUs: 'हमसे संपर्क करें',
    admin: 'प्रशासक',
    administrator: 'प्रशासक',
    adminProfile: 'एडमिन प्रोफाइल',
    dashboard: 'डैशबोर्ड',
    carsManagement: 'कार प्रबंधन',
    businessHub: 'व्यवसाय केंद्र',
    analytics: 'विश्लेषण',
    receipts: 'रसीदें',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    transactions: 'लेन-देन',
    settings: 'सिस्टम सेटिंग्स',
    staffPanel: 'स्टाफ पैनल',
    departments: 'विभाग',
    inventory: 'इन्वेंटरी',
    activityLogs: 'गतिविधि लॉग',
    branches: 'शाखाएं',
    returnToDashboard: 'डैशबोर्ड पर वापस जाएं',
    help: 'सहायता',
    support: 'समर्थन',
    tutorials: 'ट्यूटोरियल',
    documentation: 'दस्तावेज़',
    systemGuide: 'सिस्टम गाइड',
    roleBasedHelp: 'भूमिका-आधारित सहायता',
    customerService: 'ग्राहक सेवा',
    afterSales: 'बिक्री के बाद',
    warranty: 'वारंटी',
    maintenance: 'रखरखाव',
    financing: 'वित्तपोषण',
    insurance: 'बीमा',
    roadsideAssistance: 'सड़क सहायता',
    // ...add more as needed
  },
  // Add more languages as needed...
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: 'EN',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('EN');
  const t = (key: string) => translations[language][key] || key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext); 